-- =============================================================================
-- Governance: Apply Tags, Masking Policies, and Row Access Policies
-- Idempotent — safe to re-run (SET TAG and SET MASKING POLICY overwrite)
-- =============================================================================

-- -------------------------------------------------------------------------
-- 1. Apply classification tags to PII columns in customer_360
-- -------------------------------------------------------------------------
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN email SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN first_name SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN last_name SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN phone SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN address SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';


-- Apply PII tags to dim_customer
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN email SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN first_name SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN last_name SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN phone SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN address SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'PII';

-- Apply SENSITIVE tags to financial columns
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.fct_invoices
    MODIFY COLUMN amount SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'SENSITIVE';
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.fct_payments
    MODIFY COLUMN payment_amount SET TAG LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.CLASSIFICATION = 'SENSITIVE';

-- -------------------------------------------------------------------------
-- 2. Apply masking policies to PII columns in customer_360
-- -------------------------------------------------------------------------
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN email SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN first_name SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN last_name SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN phone SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.customer_360
    MODIFY COLUMN address SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;

-- Apply masking policies to PII columns in dim_customer
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN email SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN first_name SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN last_name SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN phone SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.dim_customer
    MODIFY COLUMN address SET MASKING POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.pii_string_mask;

-- -------------------------------------------------------------------------
-- 3. Apply row access policy to fct_invoices (region-based)
-- -------------------------------------------------------------------------
-- Note: fct_invoices needs a region column for direct RAP application.
-- In production, denormalize region onto the fact table or use a secure view.
-- Commented out until region column is available on fct_invoices:
-- ALTER TABLE IF EXISTS LIGHTHOUSE_PROD_ANALYTICS.MARTS.fct_invoices
--     ADD ROW ACCESS POLICY LIGHTHOUSE_PROD_ANALYTICS.GOVERNANCE.region_row_access
--     ON (region);
