-- =============================================================================
-- Governance: Apply Tags, Masking Policies, and Row Access Policies
-- Idempotent - safe to re-run (SET TAG and SET MASKING POLICY overwrite)
-- =============================================================================

SET LIGHTHOUSE_ENV = 'PROD';
SET LIGHTHOUSE_ANALYTICS_DB = 'LIGHTHOUSE_' || $LIGHTHOUSE_ENV || '_ANALYTICS';

EXECUTE IMMEDIATE 'USE DATABASE ' || $LIGHTHOUSE_ANALYTICS_DB;

ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN email SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN first_name SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN last_name SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN phone SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN address SET TAG GOVERNANCE.CLASSIFICATION = 'PII';

ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN email SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN first_name SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN last_name SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN phone SET TAG GOVERNANCE.CLASSIFICATION = 'PII';
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN address SET TAG GOVERNANCE.CLASSIFICATION = 'PII';

ALTER TABLE IF EXISTS MARTS.fct_invoices
    MODIFY COLUMN amount SET TAG GOVERNANCE.CLASSIFICATION = 'SENSITIVE';
ALTER TABLE IF EXISTS MARTS.fct_payments
    MODIFY COLUMN payment_amount SET TAG GOVERNANCE.CLASSIFICATION = 'SENSITIVE';

ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN email SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN first_name SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN last_name SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN phone SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.customer_360
    MODIFY COLUMN address SET MASKING POLICY GOVERNANCE.pii_string_mask;

ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN email SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN first_name SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN last_name SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN phone SET MASKING POLICY GOVERNANCE.pii_string_mask;
ALTER TABLE IF EXISTS MARTS.dim_customer
    MODIFY COLUMN address SET MASKING POLICY GOVERNANCE.pii_string_mask;

-- Note: fct_invoices needs a region column for direct RAP application.
-- In production, denormalize region onto the fact table or use a secure view.
-- Commented out until region column is available on fct_invoices:
-- ALTER TABLE IF EXISTS MARTS.fct_invoices
--     ADD ROW ACCESS POLICY GOVERNANCE.region_row_access
--     ON (region);
