-- =============================================================================
-- 04_grants.sql — Grant privileges per role
-- =============================================================================
-- Purpose:  Assigns database, schema, table, view, and warehouse privileges
--           to each role in the Lighthouse hierarchy. Grants are additive and
--           idempotent — re-running this script is safe.
--
-- Prerequisite: 01_databases.sql, 02_warehouses.sql, 03_roles.sql
--
-- Role privilege summary:
--   LIGHTHOUSE_READER      — SELECT on analytics/serving tables and views
--   LIGHTHOUSE_TRANSFORMER — CREATE TABLE/VIEW in analytics, use TRANSFORM_WH
--   LIGHTHOUSE_ENGINEER    — Full access to all databases and warehouses
--   LIGHTHOUSE_ADMIN       — Account-level admin privileges
-- =============================================================================

-- Inherit env from deploy.sql, or set manually if running standalone
-- SET env = 'DEV';

-- ─────────────────────────────────────────────────────────────────────────────
-- LIGHTHOUSE_READER — read-only access to analytics and serving data products
-- ─────────────────────────────────────────────────────────────────────────────

-- Database-level USAGE
GRANT USAGE ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_READER;
GRANT USAGE ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT USAGE ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;

-- Schema-level USAGE on all current and future schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;

-- SELECT on all current and future tables/views in ANALYTICS
GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_READER;

-- SELECT on all current and future tables/views in SERVING
GRANT SELECT ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON ALL VIEWS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_READER;

-- Warehouse — READER uses SERVING_WH for queries
GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_READER;

-- ─────────────────────────────────────────────────────────────────────────────
-- LIGHTHOUSE_TRANSFORMER — dbt transformation role
-- ─────────────────────────────────────────────────────────────────────────────

-- Warehouse access
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_TRANSFORMER;

-- ANALYTICS database — create and modify objects in transformation schemas
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;

-- INSERT, UPDATE, DELETE on analytics tables (for dbt incremental models)
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_TRANSFORMER;

-- ─────────────────────────────────────────────────────────────────────────────
-- LIGHTHOUSE_ENGINEER — full data engineering access
-- ─────────────────────────────────────────────────────────────────────────────

-- Warehouse access — all warehouses
GRANT USAGE ON WAREHOUSE INGESTION_WH TO ROLE LIGHTHOUSE_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_ENGINEER;
GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_ENGINEER;
GRANT USAGE ON WAREHOUSE AI_WH TO ROLE LIGHTHOUSE_ENGINEER;

-- Full privileges on all databases
GRANT ALL PRIVILEGES ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_ENGINEER;

-- Schema-level full privileges
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_ENGINEER;

-- Table/view-level full privileges
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_RAW') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_ANALYTICS') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE IDENTIFIER('LIGHTHOUSE_' || $env || '_SERVING') TO ROLE LIGHTHOUSE_ENGINEER;

-- ─────────────────────────────────────────────────────────────────────────────
-- LIGHTHOUSE_ADMIN — account-level administration
-- ─────────────────────────────────────────────────────────────────────────────

-- Account-level privileges
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
