-- =============================================================================
-- 04_grants.sql — Grant privileges per role
-- =============================================================================
-- Assigns database, schema, table, view, and warehouse privileges to each
-- role in the Lighthouse hierarchy. Grants are additive and idempotent.
--
-- Prerequisite: 01_databases.sql, 02_warehouses.sql, 03_roles.sql
-- Usage:        Run standalone or via deploy.sql. Change 'DEV' below as needed.
-- =============================================================================

DECLARE
    env VARCHAR DEFAULT 'DEV';
    db_raw VARCHAR;
    db_analytics VARCHAR;
    db_serving VARCHAR;
BEGIN
    db_raw := 'LIGHTHOUSE_' || :env || '_RAW';
    db_analytics := 'LIGHTHOUSE_' || :env || '_ANALYTICS';
    db_serving := 'LIGHTHOUSE_' || :env || '_SERVING';

    -- ─────────────────────────────────────────────────────────────────────
    -- READER — read-only on analytics and serving
    -- ─────────────────────────────────────────────────────────────────────
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_READER;

    -- ─────────────────────────────────────────────────────────────────────
    -- TRANSFORMER — dbt transformation role
    -- ─────────────────────────────────────────────────────────────────────
    GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_TRANSFORMER;
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    -- TRANSFORMER needs SELECT on RAW for dbt sources
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';

    -- ─────────────────────────────────────────────────────────────────────
    -- ENGINEER — full access to all databases and warehouses
    -- ─────────────────────────────────────────────────────────────────────
    GRANT USAGE ON WAREHOUSE INGESTION_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE AI_WH TO ROLE LIGHTHOUSE_ENGINEER;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';

    -- ─────────────────────────────────────────────────────────────────────
    -- ADMIN — account-level administration
    -- ─────────────────────────────────────────────────────────────────────
    GRANT MANAGE GRANTS ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE DATABASE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE ROLE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;

    RETURN 'Grants applied for environment: ' || :env;
END;
