-- =============================================================================
-- 07_integrations.sql — Storage and API integrations
-- =============================================================================
-- Purpose:  Defines external integrations for production ingestion patterns.
--
--           IMPORTANT: Storage integrations and API integrations require
--           ACCOUNTADMIN privileges and are NOT available on Snowflake trial
--           accounts. These definitions are provided as documented templates
--           that can be uncommented and configured when deploying to a
--           production Snowflake account.
--
--           For the demo/trial environment, all ingestion uses internal stages
--           (see 06_stages.sql) with PUT + COPY INTO.
--
-- Prerequisite: 03_roles.sql (LIGHTHOUSE_ADMIN role)
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Storage Integration — AWS S3
-- ─────────────────────────────────────────────────────────────────────────────
-- Enables external stage access for batch file ingestion from S3 buckets.
-- Required for production Partner Feeds and Knowledge Base ingestion.
--
-- To activate:
--   1. Uncomment the CREATE STORAGE INTEGRATION block below
--   2. Replace placeholder values with your AWS account details
--   3. Execute as ACCOUNTADMIN
--   4. Run DESC INTEGRATION to get the IAM role ARN for trust policy setup
--
-- CREATE OR REPLACE STORAGE INTEGRATION lighthouse_s3_integration
--     TYPE = EXTERNAL_STAGE
--     STORAGE_PROVIDER = 'S3'
--     ENABLED = TRUE
--     STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<aws_account_id>:role/lighthouse-snowflake-role'
--     STORAGE_ALLOWED_LOCATIONS = (
--         's3://nordhjem-partner-feeds/',
--         's3://nordhjem-knowledge-base/',
--         's3://nordhjem-iot-archive/'
--     )
--     COMMENT = 'S3 integration for NordHjem external data sources';
--
-- -- Grant usage to the engineering role
-- GRANT USAGE ON INTEGRATION lighthouse_s3_integration TO ROLE LIGHTHOUSE_ENGINEER;

-- ─────────────────────────────────────────────────────────────────────────────
-- Storage Integration — Azure Blob (alternative)
-- ─────────────────────────────────────────────────────────────────────────────
-- Alternative for Azure-based deployments.
--
-- CREATE OR REPLACE STORAGE INTEGRATION lighthouse_azure_integration
--     TYPE = EXTERNAL_STAGE
--     STORAGE_PROVIDER = 'AZURE'
--     ENABLED = TRUE
--     AZURE_TENANT_ID = '<azure_tenant_id>'
--     STORAGE_ALLOWED_LOCATIONS = (
--         'azure://nordhjemstorage.blob.core.windows.net/partner-feeds/',
--         'azure://nordhjemstorage.blob.core.windows.net/knowledge-base/'
--     )
--     COMMENT = 'Azure Blob integration for NordHjem external data sources';

-- ─────────────────────────────────────────────────────────────────────────────
-- API Integration — Cortex AI Features
-- ─────────────────────────────────────────────────────────────────────────────
-- Cortex Analyst and Cortex Search are built-in Snowflake features that do
-- not require explicit API integrations in most configurations. They use the
-- warehouse specified in the service/query definition (AI_WH).
--
-- If your deployment requires external API access (e.g., for custom LLM
-- endpoints or external model serving), an API integration would be defined
-- here:
--
-- CREATE OR REPLACE API INTEGRATION lighthouse_cortex_api
--     API_PROVIDER = EXTERNAL
--     API_ALLOWED_PREFIXES = ('https://api.nordhjem-ai.example.com/')
--     ENABLED = TRUE
--     COMMENT = 'API integration for external AI/ML model endpoints';
--
-- GRANT USAGE ON INTEGRATION lighthouse_cortex_api TO ROLE LIGHTHOUSE_ENGINEER;

-- ─────────────────────────────────────────────────────────────────────────────
-- Placeholder — confirms script executed successfully
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 'Integration templates loaded — uncomment and configure for production deployment' AS status;
