-- =============================================================================
-- deploy.sql — Lighthouse infrastructure deployment (all-in-one)
-- =============================================================================
-- Purpose:  Provisions a complete Lighthouse environment in one script.
--           Works in Snowsight SQL files, SnowSQL, or any SQL client.
--
-- Usage:    Change the env variable below to your target environment,
--           then select all and run.
--
-- Environment: Valid values: DEV, STAGING, PROD
-- Idempotency: All statements use IF NOT EXISTS or OR REPLACE — safe to re-run.
-- =============================================================================

DECLARE
    env VARCHAR DEFAULT 'DEV';  -- ← Change this to STAGING or PROD as needed
    db_raw VARCHAR;
    db_analytics VARCHAR;
    db_serving VARCHAR;
BEGIN
    db_raw := 'LIGHTHOUSE_' || :env || '_RAW';
    db_analytics := 'LIGHTHOUSE_' || :env || '_ANALYTICS';
    db_serving := 'LIGHTHOUSE_' || :env || '_SERVING';

    -- ═════════════════════════════════════════════════════════════════════
    -- 1. DATABASES
    -- ═════════════════════════════════════════════════════════════════════

    EXECUTE IMMEDIATE 'CREATE DATABASE IF NOT EXISTS ' || :db_raw;
    EXECUTE IMMEDIATE 'CREATE DATABASE IF NOT EXISTS ' || :db_analytics;
    EXECUTE IMMEDIATE 'CREATE DATABASE IF NOT EXISTS ' || :db_serving;

    -- ═════════════════════════════════════════════════════════════════════
    -- 2. WAREHOUSES (environment-independent)
    -- ═════════════════════════════════════════════════════════════════════

    CREATE WAREHOUSE IF NOT EXISTS INGESTION_WH
        WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE COMMENT = 'Lighthouse ingestion workloads';

    CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
        WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE COMMENT = 'Lighthouse transformation workloads — dbt build';

    CREATE WAREHOUSE IF NOT EXISTS SERVING_WH
        WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE COMMENT = 'Lighthouse serving workloads — Streamlit, BI, Dynamic Tables';

    CREATE WAREHOUSE IF NOT EXISTS AI_WH
        WITH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE COMMENT = 'Lighthouse AI workloads — Cortex Analyst, Cortex Search';

    -- ═════════════════════════════════════════════════════════════════════
    -- 3. ROLES (environment-independent)
    -- ═════════════════════════════════════════════════════════════════════

    CREATE ROLE IF NOT EXISTS LIGHTHOUSE_READER COMMENT = 'Read-only access to analytics and serving';
    CREATE ROLE IF NOT EXISTS LIGHTHOUSE_TRANSFORMER COMMENT = 'dbt transformation role';
    CREATE ROLE IF NOT EXISTS LIGHTHOUSE_ENGINEER COMMENT = 'Data engineering role — full access';
    CREATE ROLE IF NOT EXISTS LIGHTHOUSE_ADMIN COMMENT = 'Platform admin role';

    GRANT ROLE LIGHTHOUSE_READER TO ROLE LIGHTHOUSE_TRANSFORMER;
    GRANT ROLE LIGHTHOUSE_TRANSFORMER TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT ROLE LIGHTHOUSE_ENGINEER TO ROLE LIGHTHOUSE_ADMIN;
    GRANT ROLE LIGHTHOUSE_ADMIN TO ROLE SYSADMIN;

    -- ═════════════════════════════════════════════════════════════════════
    -- 4. GRANTS
    -- ═════════════════════════════════════════════════════════════════════

    -- READER
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_READER';
    GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_READER;

    -- TRANSFORMER
    GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_TRANSFORMER;
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    -- TRANSFORMER needs SELECT on RAW for dbt sources
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_TRANSFORMER';

    -- ENGINEER
    GRANT USAGE ON WAREHOUSE INGESTION_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE SERVING_WH TO ROLE LIGHTHOUSE_ENGINEER;
    GRANT USAGE ON WAREHOUSE AI_WH TO ROLE LIGHTHOUSE_ENGINEER;
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_raw || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_analytics || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ' || :db_serving || ' TO ROLE LIGHTHOUSE_ENGINEER';

    -- ADMIN
    GRANT MANAGE GRANTS ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE DATABASE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE ROLE ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;
    GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE LIGHTHOUSE_ADMIN;

    -- ═════════════════════════════════════════════════════════════════════
    -- 5. SCHEMAS
    -- ═════════════════════════════════════════════════════════════════════

    -- RAW schemas
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_raw || '.OLTP';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_raw || '.CRM';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_raw || '.IOT';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_raw || '.PARTNER_FEEDS';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_raw || '.KNOWLEDGE_BASE';

    -- ANALYTICS schemas
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.STAGING';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.INTERMEDIATE';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.MARTS';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.SNAPSHOTS';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.SEMANTIC';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.TEST_RESULTS';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_analytics || '.GOVERNANCE';

    -- SERVING schemas
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :db_serving || '.REALTIME';

    -- ═════════════════════════════════════════════════════════════════════
    -- 6. STAGES
    -- ═════════════════════════════════════════════════════════════════════

    EXECUTE IMMEDIATE 'CREATE OR REPLACE STAGE ' || :db_raw || '.OLTP.oltp_stage';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE STAGE ' || :db_raw || '.CRM.crm_stage';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE STAGE ' || :db_raw || '.IOT.iot_stage';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE STAGE ' || :db_raw || '.PARTNER_FEEDS.partner_stage';
    EXECUTE IMMEDIATE 'CREATE OR REPLACE STAGE ' || :db_raw || '.KNOWLEDGE_BASE.kb_stage';

    -- ═════════════════════════════════════════════════════════════════════
    -- 7. FILE FORMATS
    -- ═════════════════════════════════════════════════════════════════════

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.OLTP.csv_format
         TYPE = ''CSV'' FIELD_DELIMITER = '','' SKIP_HEADER = 1
         FIELD_OPTIONALLY_ENCLOSED_BY = ''"''
         NULL_IF = ('''', ''NULL'', ''null'', ''\\N'')
         EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE
         ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE';

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.CRM.csv_format
         TYPE = ''CSV'' FIELD_DELIMITER = '','' SKIP_HEADER = 1
         FIELD_OPTIONALLY_ENCLOSED_BY = ''"''
         NULL_IF = ('''', ''NULL'', ''null'', ''\\N'')
         EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE
         ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE';

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.IOT.json_format
         TYPE = ''JSON'' STRIP_OUTER_ARRAY = TRUE STRIP_NULL_VALUES = FALSE';

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.PARTNER_FEEDS.csv_format
         TYPE = ''CSV'' FIELD_DELIMITER = '','' SKIP_HEADER = 1
         FIELD_OPTIONALLY_ENCLOSED_BY = ''"''
         NULL_IF = ('''', ''NULL'', ''null'', ''\\N'')
         EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE
         ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE';

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.PARTNER_FEEDS.parquet_format
         TYPE = ''PARQUET'' COMPRESSION = ''SNAPPY''';

    EXECUTE IMMEDIATE
        'CREATE OR REPLACE FILE FORMAT ' || :db_raw || '.KNOWLEDGE_BASE.csv_format
         TYPE = ''CSV'' FIELD_DELIMITER = '','' SKIP_HEADER = 1
         FIELD_OPTIONALLY_ENCLOSED_BY = ''"''
         NULL_IF = ('''', ''NULL'', ''null'', ''\\N'')
         EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE';

    -- ═════════════════════════════════════════════════════════════════════
    -- DONE
    -- ═════════════════════════════════════════════════════════════════════

    RETURN 'Lighthouse infrastructure deployment complete for environment: ' || :env;
END;