-- =============================================================================
-- Cost Monitoring: Resource Monitors per Warehouse
-- =============================================================================

CREATE OR REPLACE RESOURCE MONITOR ingestion_wh_monitor
    WITH CREDIT_QUOTA = 50
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE IF EXISTS INGESTION_WH SET RESOURCE_MONITOR = ingestion_wh_monitor;

CREATE OR REPLACE RESOURCE MONITOR transform_wh_monitor
    WITH CREDIT_QUOTA = 200
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE IF EXISTS TRANSFORM_WH SET RESOURCE_MONITOR = transform_wh_monitor;

CREATE OR REPLACE RESOURCE MONITOR serving_wh_monitor
    WITH CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE IF EXISTS SERVING_WH SET RESOURCE_MONITOR = serving_wh_monitor;

CREATE OR REPLACE RESOURCE MONITOR ai_wh_monitor
    WITH CREDIT_QUOTA = 150
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE IF EXISTS AI_WH SET RESOURCE_MONITOR = ai_wh_monitor;
